### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by imtira** [Glenwing/glenwing.github.io#2]
Hi!

Could you add a license to your project? I'd like to use some components of it, but I don't know what your policy is.

Cheers.

**Comment by Glenwing** [comment]
> Hi!
> 
> Could you add a license to your project? I'd like to use some components of it, but I don't know what your policy is.
> 
> Cheers.

It's just code for a personal website, but I can put it under CC-BY. I'm curious which components you're interested in though, since there isn't much here that's designed to be included in other projects.

**Comment by imtira** [comment]
There's a few cool utilities I'd like to pull out of it, or at least take inspiration from. Thought it'd be better to be safe than sorry :)
